[project]
name = "gym-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "openai>=2.8.1",
    "pydantic-ai>=1.23.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
